Repository jenkins-infra/kubernetes-management, pull requests merged in 2023-03, with the labels that each got.

#3660 feat(cik8s,doks) increase the max. pod quotas for jenkins-agents namespaces
  clusters/cik8s.yaml
  clusters/doks.yaml
Labels: enhancement

#3662 Add `gatsby-plugin-jenkins-layout` job to infra.ci.jenkins.io
  config/ext_jenkins-infra-jobs.yaml
Labels: enhancement

#3709 chore(updatecli) track the maven tool version for infra.ci.jenkins.io
  updatecli/updatecli.d/charts/jenkins-infra-tools-maven.yaml
Labels: chore

#3734 feat(privatek8s): track GitHub hooks IPs
  config/ext_public-nginx-ingress_privatek8s.yaml
  updatecli/updatecli.d/allowed-github-hooks-ips.yaml
Labels: public-nginx, github-hooks-ips, privatek8s
